export const TOGGLE_TEMA='TOGGLE_TEMA';
// TYPES PER FETCH DI LOGIN E REGISTER
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGOUT = "LOGOUT";
//TYPES PER WALLET
export const WALLET_REQUEST = "WALLET_REQUEST";
export const WALLET_SUCCESS = "WALLET_SUCCESS";
export const WALLET_FAILURE = "WALLET_FAILURE";
//TYPES PER CRYPTO-COMPARE
//AZIONI PER IL PREZZO
export const  CRYPTO_COMPARE_PREZZO_REQUEST= "CRYPTO_COMPARE_PREZZO_REQUEST";
export const  CRYPTO_COMPARE_PREZZO_SUCCESS= "CRYPTO_COMPARE_PREZZO_SUCCESS";
export const  CRYPTO_COMPARE_PREZZO_FAILURE= "CRYPTO_COMPARE_PREZZO_FAILURE";
//AZIONI PER LA HISTORY
export const  CRYPTO_COMPARE_HISTORY_REQUEST= "CRYPTO_COMPARE_HISTORY_REQUEST";
export const  CRYPTO_COMPARE_HISTORY_SUCCESS= "CRYPTO_COMPARE_HISTORY_SUCCESS";
export const  CRYPTO_COMPARE_HISTORY_FAILURE= "CRYPTO_COMPARE_HISTORY_FAILURE";
//AZIONI PER VOLUME
export const  CRYPTO_COMPARE_VOLUME_REQUEST= "CRYPTO_COMPARE_VOLUME_REQUEST";
export const  CRYPTO_COMPARE_VOLUME_SUCCESS= "CRYPTO_COMPARE_VOLUME_SUCCESS";
export const  CRYPTO_COMPARE_VOLUME_FAILURE= "CRYPTO_COMPARE_VOLUME_FAILURE";

//TYPES PER TRANSACTION
export const TRANSACTION_REQUEST = "TRANSACTION_REQUEST";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_FAILURE = "TRANSACTION_FAILURE";